openapi: 3.0.2
info:
  title: Query Suggestions API
  description: API powering the Query Suggestions feature of Algolia.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://query-suggestions.{region}.algolia.com
    variables:
      region:
        enum:
          - us
          - eu
        default: us
security:
  - appId: []
    apiKey: []
tags:
  - name: advanced
    x-displayName: Advanced
    description: Advanced operations.
  - name: configurations
    x-displayName: Configurations
    description: Manage Query Suggestions configurations.
x-tagGroups:
  - name: General
    tags:
      - configurations
  - name: Others
    tags:
      - advanced
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/configs:
    $ref: 'paths/qsConfigs.yml'
  /1/configs/{indexName}:
    $ref: 'paths/qsConfig.yml'
  /1/configs/{indexName}/status:
    $ref: 'paths/getConfigurationStatus.yml'
  /1/logs/{indexName}:
    $ref: 'paths/getLogFile.yml'
