// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package usage

import (
	"encoding/json"
	"fmt"
)

// GetUsage400ResponseErrorErrorsInner struct for GetUsage400ResponseErrorErrorsInner.
type GetUsage400ResponseErrorErrorsInner struct {
	Code     *string `json:"code,omitempty"`
	Message  string  `json:"message"`
	Line     *int32  `json:"line,omitempty"`
	Position *int32  `json:"position,omitempty"`
}

type GetUsage400ResponseErrorErrorsInnerOption func(f *GetUsage400ResponseErrorErrorsInner)

func WithGetUsage400ResponseErrorErrorsInnerCode(val string) GetUsage400ResponseErrorErrorsInnerOption {
	return func(f *GetUsage400ResponseErrorErrorsInner) {
		f.Code = &val
	}
}

func WithGetUsage400ResponseErrorErrorsInnerLine(val int32) GetUsage400ResponseErrorErrorsInnerOption {
	return func(f *GetUsage400ResponseErrorErrorsInner) {
		f.Line = &val
	}
}

func WithGetUsage400ResponseErrorErrorsInnerPosition(val int32) GetUsage400ResponseErrorErrorsInnerOption {
	return func(f *GetUsage400ResponseErrorErrorsInner) {
		f.Position = &val
	}
}

// NewGetUsage400ResponseErrorErrorsInner instantiates a new GetUsage400ResponseErrorErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewGetUsage400ResponseErrorErrorsInner(message string, opts ...GetUsage400ResponseErrorErrorsInnerOption) *GetUsage400ResponseErrorErrorsInner {
	this := &GetUsage400ResponseErrorErrorsInner{}
	this.Message = message
	for _, opt := range opts {
		opt(this)
	}
	return this
}

// NewEmptyGetUsage400ResponseErrorErrorsInner return a pointer to an empty GetUsage400ResponseErrorErrorsInner object.
func NewEmptyGetUsage400ResponseErrorErrorsInner() *GetUsage400ResponseErrorErrorsInner {
	return &GetUsage400ResponseErrorErrorsInner{}
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetUsage400ResponseErrorErrorsInner) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage400ResponseErrorErrorsInner) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetUsage400ResponseErrorErrorsInner) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetUsage400ResponseErrorErrorsInner) SetCode(v string) *GetUsage400ResponseErrorErrorsInner {
	o.Code = &v
	return o
}

// GetMessage returns the Message field value.
func (o *GetUsage400ResponseErrorErrorsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetUsage400ResponseErrorErrorsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value.
func (o *GetUsage400ResponseErrorErrorsInner) SetMessage(v string) *GetUsage400ResponseErrorErrorsInner {
	o.Message = v
	return o
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *GetUsage400ResponseErrorErrorsInner) GetLine() int32 {
	if o == nil || o.Line == nil {
		var ret int32
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage400ResponseErrorErrorsInner) GetLineOk() (*int32, bool) {
	if o == nil || o.Line == nil {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *GetUsage400ResponseErrorErrorsInner) HasLine() bool {
	if o != nil && o.Line != nil {
		return true
	}

	return false
}

// SetLine gets a reference to the given int32 and assigns it to the Line field.
func (o *GetUsage400ResponseErrorErrorsInner) SetLine(v int32) *GetUsage400ResponseErrorErrorsInner {
	o.Line = &v
	return o
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *GetUsage400ResponseErrorErrorsInner) GetPosition() int32 {
	if o == nil || o.Position == nil {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsage400ResponseErrorErrorsInner) GetPositionOk() (*int32, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *GetUsage400ResponseErrorErrorsInner) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *GetUsage400ResponseErrorErrorsInner) SetPosition(v int32) *GetUsage400ResponseErrorErrorsInner {
	o.Position = &v
	return o
}

func (o GetUsage400ResponseErrorErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if o.Line != nil {
		toSerialize["line"] = o.Line
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal GetUsage400ResponseErrorErrorsInner: %w", err)
	}

	return serialized, nil
}

func (o GetUsage400ResponseErrorErrorsInner) String() string {
	out := ""
	out += fmt.Sprintf("  code=%v\n", o.Code)
	out += fmt.Sprintf("  message=%v\n", o.Message)
	out += fmt.Sprintf("  line=%v\n", o.Line)
	out += fmt.Sprintf("  position=%v\n", o.Position)
	return fmt.Sprintf("GetUsage400ResponseErrorErrorsInner {\n%s}", out)
}
