name: Setup

description: Setup CI environment.

runs:
  using: composite
  steps:
    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11.0.4
        cache: gradle

    - name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Restore cache
      uses: ./.github/actions/cache

    - name: Setting diff outputs variables
      id: diff
      shell: bash
      run: |
        echo "::set-output name=GITHUB_ACTIONS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- .github/actions .github/workflows | wc -l)"

        echo "::set-output name=SPECS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- specs | wc -l)"
        echo "::set-output name=COMMON_SPECS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- specs/common | wc -l)"

        echo "::set-output name=TESTS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- tests | wc -l)"

        echo "::set-output name=SCRIPTS_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- scripts | wc -l)"

        echo "::set-output name=JS_CLIENT_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- clients/algoliasearch-client-javascript | wc -l)"
        echo "::set-output name=JS_TEMPLATE_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- templates/javascript | wc -l)"

        echo "::set-output name=JAVA_CLIENT_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- clients/algoliasearch-client-java-2 | wc -l)"
        echo "::set-output name=JAVA_TEMPLATE_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- templates/java | wc -l)"

        echo "::set-output name=PHP_CLIENT_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- clients/algoliasearch-client-php | wc -l)"
        echo "::set-output name=PHP_TEMPLATE_CHANGED::$(git diff --shortstat origin/${{ github.base_ref }}..HEAD -- templates/php | wc -l)"

    - name: Compute specs matrix
      id: spec-matrix
      shell: bash
      run: |
        base_changed=${{ github.ref == 'refs/heads/main' || steps.diff.outputs.GITHUB_ACTIONS_CHANGED > 0 || steps.diff.outputs.SCRIPTS_CHANGED > 0 || steps.diff.outputs.COMMON_SPECS_CHANGED > 0 }}

        matrix=$(./scripts/ci/create-spec-matrix.sh $base_changed ${{ github.base_ref }})

        if [[ $matrix == '{"client":["no-run"]}' ]]; then
          run="false"
        else
          run="true"
        fi

        echo "::set-output name=MATRIX::$matrix"
        echo "::set-output name=RUN_SPECS::$run"

    - name: Compute the JS client build matrix
      id: js-matrix
      shell: bash
      run: |
        base_changed=${{ github.ref == 'refs/heads/main' || steps.diff.outputs.GITHUB_ACTIONS_CHANGED > 0 || steps.diff.outputs.COMMON_SPECS_CHANGED > 0 || steps.diff.outputs.SCRIPTS_CHANGED > 0 || steps.diff.outputs.JS_TEMPLATE_CHANGED > 0 }}

        matrix=$(./scripts/ci/create-client-matrix.sh javascript $base_changed ${{ github.base_ref }})

        if [[ $matrix == '{"client":["no-run"]}' ]]; then
          run="false"
        else
          run="true"
        fi

        echo "::set-output name=MATRIX::$matrix"
        echo "::set-output name=RUN_CLIENT::$run"

    - name: Compute the Java client build matrix
      id: java-matrix
      shell: bash
      run: |
        base_changed=${{ github.ref == 'refs/heads/main' || steps.diff.outputs.GITHUB_ACTIONS_CHANGED > 0 || steps.diff.outputs.COMMON_SPECS_CHANGED > 0 || steps.diff.outputs.SCRIPTS_CHANGED > 0 || steps.diff.outputs.JAVA_TEMPLATE_CHANGED > 0 }}

        matrix=$(./scripts/ci/create-client-matrix.sh java $base_changed ${{ github.base_ref }})

        if [[ $matrix == '{"client":["no-run"]}' ]]; then
          run="false"
        else
          run="true"
        fi

        echo "::set-output name=MATRIX::$matrix"
        echo "::set-output name=RUN_CLIENT::$run"

    - name: Compute the PHP client build matrix
      id: php-matrix
      shell: bash
      run: |
        base_changed=${{ github.ref == 'refs/heads/main' || steps.diff.outputs.GITHUB_ACTIONS_CHANGED > 0 || steps.diff.outputs.COMMON_SPECS_CHANGED > 0 || steps.diff.outputs.SCRIPTS_CHANGED > 0 || steps.diff.outputs.PHP_TEMPLATE_CHANGED > 0 }}

        matrix=$(./scripts/ci/create-client-matrix.sh php $base_changed ${{ github.base_ref }})

        if [[ $matrix == '{"client":["no-run"]}' ]]; then
          run="false"
        else
          run="true"
        fi

        echo "::set-output name=MATRIX::$matrix"
        echo "::set-output name=RUN_CLIENT::$run"

outputs:
  RUN_SPECS:
    description: Whether to run specs or not
    value: ${{ steps.spec-matrix.outputs.RUN_SPECS }}

  SPECS_MATRIX:
    description: Generate the matrix for specs
    value: ${{ steps.spec-matrix.outputs.MATRIX }}

  RUN_JS:
    description: Whether to run js client or not
    value: ${{ steps.js-matrix.outputs.RUN_CLIENT }}

  JS_MATRIX:
    description: Generate the matrix for the Javascript client
    value: ${{ steps.js-matrix.outputs.MATRIX }}

  RUN_JAVA:
    description: Whether to run java client or not
    value: ${{ steps.java-matrix.outputs.RUN_CLIENT }}

  JAVA_MATRIX:
    description: Generate the matrix for the Java client
    value: ${{ steps.java-matrix.outputs.MATRIX }}

  RUN_PHP:
    description: Whether to run php client or not
    value: ${{ steps.php-matrix.outputs.RUN_CLIENT }}

  PHP_MATRIX:
    description: Generate the matrix for the PHP client
    value: ${{ steps.php-matrix.outputs.MATRIX }}

  RUN_CTS:
    description: Determine if the `cts` job should run
    value: ${{ github.ref_name == 'main' || steps.diff.outputs.GITHUB_ACTIONS_CHANGED > 0 || steps.diff.outputs.SCRIPTS_CHANGED > 0 || steps.diff.outputs.SPECS_CHANGED > 0 || steps.diff.outputs.TESTS_CHANGED > 0 || steps.diff.outputs.JS_CLIENT_CHANGED > 0 || steps.diff.outputs.JS_TEMPLATE_CHANGED > 0 || steps.diff.outputs.JAVA_CLIENT_CHANGED > 0 || steps.diff.outputs.JAVA_TEMPLATE_CHANGED > 0 }}
