name: Setup

description: Setup CI environment.

inputs:
  type:
    description: Type of setup, `minimal` will only setup the JavaScript monorepo, `matrix` will set the run variables.
    required: false
  workflow_name:
    description: Name of the workflow that is executing this action.
    required: false
  language:
    description: the language for which to install deps
    required: false

runs:
  using: composite
  steps:
    - name: Read current GitHub Actions cache version
      shell: bash
      run: |
        echo "CACHE_VERSION=$(< .github/.cache_version)" >> $GITHUB_ENV

    # Java for code generation
    - name: Install Java
      if: inputs.type != 'minimal'
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11.0.4
        cache: gradle

    - name: Validate gradle wrapper
      if: inputs.type != 'minimal'
      uses: gradle/wrapper-validation-action@v1

    - name: Download Java formatter
      if: inputs.type != 'minimal'
      shell: bash
      run: curl -L "https://github.com/google/google-java-format/releases/download/v1.13.0/google-java-format-1.13.0-all-deps.jar" > /tmp/java-formatter.jar

    # JavaScript for monorepo and tooling
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - name: Restore Yarn
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir || '.yarn/cache' }}
        # let yarn handle the cache hash
        key: yarn-cache-${{ env.CACHE_VERSION }}

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ env.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}

    - name: Install JavaScript dependencies
      shell: bash
      run: yarn install

    # JavaScript client deps
    - name: Get yarn js-client cache directory path
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      id: yarn-cache-dir-client
      run: echo "::set-output name=dir::$(cd clients/algoliasearch-client-javascript && yarn config get cacheFolder)"

    - name: Restore Yarn js-client
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-client.outputs.dir || 'clients/algoliasearch-client-javascript/.yarn/cache' }}
        # let yarn handle the cache hash
        key: yarn-cache-client-${{ env.CACHE_VERSION }}

    - name: Cache js-client node modules
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/cache@v3
      with:
        path: clients/algoliasearch-client-javascript/node_modules
        key: node-modules-client-${{ env.CACHE_VERSION }}-${{ hashFiles('clients/algoliasearch-client-javascript/yarn.lock') }}

    - name: Install JavaScript client dependencies
      if: ${{ inputs.language == 'javascript' }}
      shell: bash
      run: cd clients/algoliasearch-client-javascript && yarn install

    # PHP deps
    - name: Run composer update
      if: ${{ inputs.language == 'php' }}
      shell: bash
      run: |
        composer update --working-dir=clients/algoliasearch-client-php
        composer dump-autoload --working-dir=clients/algoliasearch-client-php

    # Computing jobs that should run
    - name: Setting diff outputs variables
      if: inputs.type == 'matrix'
      id: diff
      shell: bash
      run: |
        previousCommit=${{ github.event.before }}
        baseRef=${{ github.base_ref }}
        origin=$( [[ -z $baseRef ]] && echo $previousCommit || echo "origin/$baseRef" )

        yarn workspace scripts setRunVariables "$origin"

    - name: Compute specs matrix
      if: inputs.type == 'matrix'
      id: spec-matrix
      shell: bash
      run: yarn workspace scripts createMatrix ${{ steps.diff.outputs.ORIGIN_BRANCH }}

    - name: Compute the client codegen matrix
      if: inputs.type == 'matrix'
      id: gen-matrix
      shell: bash
      run: yarn workspace scripts createMatrix ${{ steps.diff.outputs.ORIGIN_BRANCH }} clients

    - name: Check if JavaScript utils should run
      if: inputs.type == 'matrix'
      id: js-utils
      shell: bash
      run: |
        if ${{ steps.gen-matrix.outputs.RUN_GEN_JAVASCRIPT || steps.diff.outputs.JAVASCRIPT_UTILS_CHANGED > 0 }}; then
          echo "Running JavaScript utils: true"
          echo "::set-output name=RUN_JS_UTILS::true"
        fi

outputs:
  RUN_SCRIPTS:
    description: Determine if the `scripts` job should run
    value: ${{ steps.diff.outputs.GITHUB_ACTIONS_CHANGED > 0 || steps.diff.outputs.SCRIPTS_CHANGED > 0 }}

  SPECS_MATRIX:
    description: The generated `specs` matrix
    value: ${{ steps.spec-matrix.outputs.MATRIX }}

  RUN_GEN:
    description: Determine if the `client_gen` job should run
    value: ${{ steps.gen-matrix.outputs.RUN_GEN }}
  GEN_MATRIX:
    description: The generated `client_gen` matrix
    value: ${{ steps.gen-matrix.outputs.GEN_MATRIX }}

  RUN_GEN_JAVASCRIPT:
    description: Indicates if we plan to run the job for this language
    value: ${{ steps.gen-matrix.outputs.RUN_GEN_JAVASCRIPT }}
  RUN_GEN_JAVA:
    description: Indicates if we plan to run the job for this language
    value: ${{ steps.gen-matrix.outputs.RUN_GEN_JAVA }}
  RUN_GEN_PHP:
    description: Indicates if we plan to run the job for this language
    value: ${{ steps.gen-matrix.outputs.RUN_GEN_PHP }}

  RUN_JS_UTILS:
    description: Whether to build JS client common folders when RUN_JS is false
    value: ${{ steps.js-utils.outputs.RUN_JS_UTILS }}

  RUN_CODEGEN:
    description: Determine if the `codegen` job should run
    value: ${{ steps.gen-matrix.outputs.RUN_GEN == 'true' }}
