version: "2"
run:
  concurrency: 2
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godoclint
    - inamedparam
    - intrange
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nonamedreturns
    - perfsprint
    - recvcheck
    - tagliatelle
    - varnamelen
    - wsl
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks: ["all", "-ST1005", "-ST1016"]
  exclusions:
    generated: disable
    presets:
      - comments
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 150
