language: go

go:
  - "1.11"
  - "1.12"
  - "1.13"

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
  - make deps
  - make generate

script:
  - make lint
  - make test
