language: go

os:
  - linux

go:
  - "1.7"
  - "1.10"

before_install:
  - mkdir -p /home/travis/gopath/{src,bin,pkg}
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u github.com/rakyll/gotest

install:
  - make deps
  - make install

script:
  - make test
