all: generate deps lint

generate:
	go generate ./...

deps:
	go get ./...

lint:
	golangci-lint run ./...

unit-tests:
	go test -v ./algolia/...

integration-tests:
	go test -v ./cts/...

integration-tests-community:
	go test -v -tags community ./cts/...

clean:
	rm -f `grep -R -l --include \*.go -F 'DO NOT EDIT' * | grep -v -F 'algolia/internal/gen/'`
	go clean -cache -testcache ./...
