[build]
  command="BUNDLE_WITH_DOC=true DOCKER=true yarn cli build specs all && yarn website:build"
  publish="website/build"
  ignore="git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- website/"

[build.environment]
  YARN_VERSION = "3.1.1"
