[build]
  command="BUNDLE_WITH_DOC=true DOCKER=true yarn cli build specs all && yarn website:build"
  publish="website/build"
  ignore="bash ./scripts/website/netlify-ignore-build.sh"

[build.environment]
  YARN_VERSION = "3.1.1"
