// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package agentStudio

import (
	"encoding/json"
	"fmt"
)

// Facets Order of facet names.
type Facets struct {
	Order                []string       `json:"order,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

type FacetsOption func(f *Facets)

func WithFacetsOrder(val []string) FacetsOption {
	return func(f *Facets) {
		f.Order = val
	}
}

// NewFacets instantiates a new Facets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewFacets(opts ...FacetsOption) *Facets {
	this := &Facets{}
	for _, opt := range opts {
		opt(this)
	}

	return this
}

// NewEmptyFacets return a pointer to an empty Facets object.
func NewEmptyFacets() *Facets {
	return &Facets{}
}

// GetOrder returns the Order field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Facets) GetOrder() []string {
	if o == nil {
		var ret []string

		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned.
func (o *Facets) GetOrderOk() ([]string, bool) {
	if o == nil || o.Order == nil {
		return nil, false
	}

	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *Facets) HasOrder() bool {
	if o != nil && o.Order != nil {
		return true
	}

	return false
}

// SetOrder gets a reference to the given []string and assigns it to the Order field.
func (o *Facets) SetOrder(v []string) *Facets {
	o.Order = v

	return o
}

func (o *Facets) SetAdditionalProperty(key string, value any) *Facets {
	if o.AdditionalProperties == nil {
		o.AdditionalProperties = make(map[string]any)
	}

	o.AdditionalProperties[key] = value

	return o
}

func (o Facets) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Facets: %w", err)
	}

	return serialized, nil
}

func (o *Facets) UnmarshalJSON(bytes []byte) error {
	raw := make(map[string]json.RawMessage)
	err := json.Unmarshal(bytes, &raw)
	if err != nil {
		return fmt.Errorf("failed to unmarshal Facets: %w", err)
	}

	if v, ok := raw["order"]; ok {
		err := json.Unmarshal(v, &o.Order)
		if err != nil {
			return fmt.Errorf("failed to unmarshal field order of Facets: %w", err)
		}

		delete(raw, "order")
	}

	o.AdditionalProperties = make(map[string]any)

	for key, val := range raw {
		var parsed any
		err := json.Unmarshal(val, &parsed)
		if err != nil {
			return fmt.Errorf("failed to unmarshal additionalProperties of Facets: %w", err)
		}

		o.AdditionalProperties[key] = parsed
	}

	return nil
}

func (o Facets) String() string {
	out := ""

	out += fmt.Sprintf("  order=%v\n", o.Order)
	for key, value := range o.AdditionalProperties {
		out += fmt.Sprintf("  %s=%v\n", key, value)
	}

	return fmt.Sprintf("Facets {\n%s}", out)
}
