// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package agentStudio

import (
	"encoding/json"
	"fmt"
)

// AllowedDomainListResponse List of allowed domains for an application.
type AllowedDomainListResponse struct {
	Domains []AllowedDomainResponse `json:"domains"`
}

// NewAllowedDomainListResponse instantiates a new AllowedDomainListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewAllowedDomainListResponse(domains []AllowedDomainResponse) *AllowedDomainListResponse {
	this := &AllowedDomainListResponse{}
	this.Domains = domains

	return this
}

// NewEmptyAllowedDomainListResponse return a pointer to an empty AllowedDomainListResponse object.
func NewEmptyAllowedDomainListResponse() *AllowedDomainListResponse {
	return &AllowedDomainListResponse{}
}

// GetDomains returns the Domains field value.
func (o *AllowedDomainListResponse) GetDomains() []AllowedDomainResponse {
	if o == nil {
		var ret []AllowedDomainResponse

		return ret
	}

	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value
// and a boolean to check if the value has been set.
func (o *AllowedDomainListResponse) GetDomainsOk() ([]AllowedDomainResponse, bool) {
	if o == nil {
		return nil, false
	}

	return o.Domains, true
}

// SetDomains sets field value.
func (o *AllowedDomainListResponse) SetDomains(v []AllowedDomainResponse) *AllowedDomainListResponse {
	o.Domains = v

	return o
}

func (o AllowedDomainListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	toSerialize["domains"] = o.Domains

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal AllowedDomainListResponse: %w", err)
	}

	return serialized, nil
}

func (o AllowedDomainListResponse) String() string {
	out := ""
	out += fmt.Sprintf("  domains=%v\n", o.Domains)

	return fmt.Sprintf("AllowedDomainListResponse {\n%s}", out)
}
