// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package agentStudio

import (
	"encoding/json"
	"fmt"
)

// FacetsUnion - struct for FacetsUnion.
type FacetsUnion struct {
	Facets        *Facets
	ArrayOfString *[]string
}

// []stringAsFacetsUnion is a convenience function that returns []string wrapped in FacetsUnion.
func ArrayOfStringAsFacetsUnion(v []string) *FacetsUnion {
	return &FacetsUnion{
		ArrayOfString: &v,
	}
}

// FacetsAsFacetsUnion is a convenience function that returns Facets wrapped in FacetsUnion.
func FacetsAsFacetsUnion(v Facets) *FacetsUnion {
	return &FacetsUnion{
		Facets: &v,
	}
}

// Unmarshal JSON data into one or more of the pointers in the struct.
func (dst *FacetsUnion) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal data into ArrayOfString
	err = json.Unmarshal(data, &dst.ArrayOfString)
	if err != nil {
		dst.ArrayOfString = nil
	}
	// try to unmarshal data into Facets
	err = json.Unmarshal(data, &dst.Facets)
	if err != nil {
		dst.Facets = nil
	}

	// check if at least one type was successfully unmarshaled
	if dst.Facets != nil {
		return nil
	}

	if dst.ArrayOfString != nil {
		return nil
	}

	return fmt.Errorf("data failed to match schemas in oneOf(FacetsUnion)")
}

// Marshal data from the first non-nil pointers in the struct to JSON.
func (src FacetsUnion) MarshalJSON() ([]byte, error) {
	if src.Facets != nil {
		serialized, err := json.Marshal(&src.Facets)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal one of Facets of FacetsUnion: %w", err)
		}

		return serialized, nil
	}

	if src.ArrayOfString != nil {
		serialized, err := json.Marshal(&src.ArrayOfString)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal one of ArrayOfString of FacetsUnion: %w", err)
		}

		return serialized, nil
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance.
func (obj FacetsUnion) GetActualInstance() any {
	if obj.Facets != nil {
		return *obj.Facets
	}

	if obj.ArrayOfString != nil {
		return *obj.ArrayOfString
	}

	// all schemas are nil
	return nil
}
