put:
  operationId: updateConfig
  description: Update the configuration of a Query Suggestions index.
  summary: Update the configuration of a Query Suggestions index.
  parameters:
    - $ref: ../../common/parameters.yml#/IndexName
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../common/parameters.yml#/QuerySuggestionsIndexParam
  responses:
    '200':
      $ref: ../../common/responses/Success.yml
    '401':
      $ref: ../../common/responses/Unauthorized.yml
    '500':
      $ref: ../../common/responses/InternalError.yml

delete:
  tags:
    - query-suggestions
  operationId: deleteConfig
  description: >
    Delete a configuration of a Query Suggestion's index.

    By deleting a configuraton, you stop all updates to the underlying query suggestion index.

    Note that when doing this, the underlying index does not change - existing suggestions remain untouched.
  summary: Delete a configuration of a Query Suggestion's index.
  parameters:
    - $ref: ../../common/parameters.yml#/IndexName
  responses:
    '200':
      $ref: ../../common/responses/Success.yml
    '401':
      $ref: ../../common/responses/Unauthorized.yml
    '403':
      $ref: ../../common/responses/MethodNotAllowed.yml
    '500':
      $ref: ../../common/responses/InternalError.yml

get:
  tags:
    - query-suggestions
  operationId: getConfig
  description: Get the configuration of a single Query Suggestions index.
  summary: Get the configuration of a single Query Suggestions index.
  parameters:
    - $ref: ../../common/parameters.yml#/IndexName
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../common/schemas/QuerySuggestionsIndex.yml#/QuerySuggestionsIndex
    '400':
      $ref: ../../common/responses/BadRequest.yml
    '401':
      $ref: ../../common/responses/Unauthorized.yml
    '403':
      $ref: ../../common/responses/MethodNotAllowed.yml
    '404':
      $ref: ../../common/responses/IndexNotFound.yml
    '500':
      $ref: ../../common/responses/InternalError.yml
