params:
  oneOf:
    - $ref: '#/modelsToRetrieveParam'
    - $ref: '#/typesToRetrieveParam'
    - $ref: '#/allParams'

allParams:
  allOf:
    - $ref: '#/modelsToRetrieveParam'
    - $ref: '#/typesToRetrieveParam'

modelsToRetrieveParam:
  type: object
  required:
    - modelsToRetrieveParam
  properties:
    modelsToRetrieve:
      type: array
      items:
        $ref: '#/modelsToRetrieve'

typesToRetrieveParam:
  type: object
  required:
    - typesToRetrieveParam
  properties:
    typesToRetrieve:
      type: array
      items:
        $ref: '#/typesToRetrieve'

modelsToRetrieve:
  type: string
  enum: [funnel_stage, order_value, affinities]

typesToRetrieve:
  type: string
  enum: [properties, segments]
