params:
  oneOf:
    - $ref: '#/modelsToRetrieveParam'
    - $ref: '#/typesToRetrieveParam'
    - $ref: '#/allParams'

allParams:
  allOf:
    - $ref: '#/modelsToRetrieveParam'
    - $ref: '#/typesToRetrieveParam'

fetchAllUserProfilesParams:
  oneOf:
    - $ref: '#/modelsToRetrieveParam'
    - $ref: '#/typesToRetrieveParam'
    - $ref: '#/nextPageTokenParam'
    - $ref: '#/previousPageTokenParam'
    - $ref: '#/limitParam'

modelsToRetrieveParam:
  type: object
  required:
    - modelsToRetrieveParam
  properties:
    modelsToRetrieve:
      type: array
      items:
        $ref: '#/modelsToRetrieve'

typesToRetrieveParam:
  type: object
  required:
    - typesToRetrieveParam
  properties:
    typesToRetrieve:
      type: array
      items:
        $ref: '#/typesToRetrieve'

nextPageTokenParam:
  type: object
  properties:
    nextPageToken:
      $ref: '#/nextPageToken'

previousPageTokenParam:
  type: object
  properties:
    previousPageToken:
      $ref: '#/previousPageToken'

limitParam:
  type: object
  properties:
    limit:
      $ref: '#/limit'

modelsToRetrieve:
  type: string
  enum: [funnel_stage, order_value, affinities]

typesToRetrieve:
  type: string
  enum: [properties, segments]

nextPageToken:
  type: string
  description: 'The token is used to navigate forward in the user list. To navigate from the current user list to the next page, the API generates the next page token and it sends the token in the response, beside the current user list. NOTE: This body param cannot be used with `previousPageToken` at the same time.'

previousPageToken:
  type: string
  description: 'The token is used to navigate backward in the user list. To navigate from the current user list to the previous page, the API generates the previous page token and it sends the token in the response, beside the current user list. NOTE: This body param cannot be used with `nextPageToken` at the same time.'

limit:
  type: integer
