// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package search

import (
	"encoding/json"
	"fmt"
)

// UpdateApiKeyResponse struct for UpdateApiKeyResponse.
type UpdateApiKeyResponse struct {
	// API key.
	Key string `json:"key"`
	// Date and time when the object was updated, in RFC 3339 format.
	UpdatedAt string `json:"updatedAt"`
}

// NewUpdateApiKeyResponse instantiates a new UpdateApiKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewUpdateApiKeyResponse(key string, updatedAt string) *UpdateApiKeyResponse {
	this := &UpdateApiKeyResponse{}
	this.Key = key
	this.UpdatedAt = updatedAt
	return this
}

// NewEmptyUpdateApiKeyResponse return a pointer to an empty UpdateApiKeyResponse object.
func NewEmptyUpdateApiKeyResponse() *UpdateApiKeyResponse {
	return &UpdateApiKeyResponse{}
}

// GetKey returns the Key field value.
func (o *UpdateApiKeyResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UpdateApiKeyResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value.
func (o *UpdateApiKeyResponse) SetKey(v string) *UpdateApiKeyResponse {
	o.Key = v
	return o
}

// GetUpdatedAt returns the UpdatedAt field value.
func (o *UpdateApiKeyResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateApiKeyResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value.
func (o *UpdateApiKeyResponse) SetUpdatedAt(v string) *UpdateApiKeyResponse {
	o.UpdatedAt = v
	return o
}

func (o UpdateApiKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	toSerialize["key"] = o.Key
	toSerialize["updatedAt"] = o.UpdatedAt
	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal UpdateApiKeyResponse: %w", err)
	}

	return serialized, nil
}

func (o UpdateApiKeyResponse) String() string {
	out := ""
	out += fmt.Sprintf("  key=%v\n", o.Key)
	out += fmt.Sprintf("  updatedAt=%v\n", o.UpdatedAt)
	return fmt.Sprintf("UpdateApiKeyResponse {\n%s}", out)
}
