// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package search

import (
	"encoding/json"
	"fmt"
)

// GetTopUserIdsResponse User IDs and clusters.
type GetTopUserIdsResponse struct {
	// Key-value pairs with cluster names as keys and lists of users with the highest number of records per cluster as values.
	TopUsers []map[string][]UserId `json:"topUsers"`
}

// NewGetTopUserIdsResponse instantiates a new GetTopUserIdsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewGetTopUserIdsResponse(topUsers []map[string][]UserId) *GetTopUserIdsResponse {
	this := &GetTopUserIdsResponse{}
	this.TopUsers = topUsers
	return this
}

// NewEmptyGetTopUserIdsResponse return a pointer to an empty GetTopUserIdsResponse object.
func NewEmptyGetTopUserIdsResponse() *GetTopUserIdsResponse {
	return &GetTopUserIdsResponse{}
}

// GetTopUsers returns the TopUsers field value.
func (o *GetTopUserIdsResponse) GetTopUsers() []map[string][]UserId {
	if o == nil {
		var ret []map[string][]UserId
		return ret
	}

	return o.TopUsers
}

// GetTopUsersOk returns a tuple with the TopUsers field value
// and a boolean to check if the value has been set.
func (o *GetTopUserIdsResponse) GetTopUsersOk() ([]map[string][]UserId, bool) {
	if o == nil {
		return nil, false
	}
	return o.TopUsers, true
}

// SetTopUsers sets field value.
func (o *GetTopUserIdsResponse) SetTopUsers(v []map[string][]UserId) *GetTopUserIdsResponse {
	o.TopUsers = v
	return o
}

func (o GetTopUserIdsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	toSerialize["topUsers"] = o.TopUsers
	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal GetTopUserIdsResponse: %w", err)
	}

	return serialized, nil
}

func (o GetTopUserIdsResponse) String() string {
	out := ""
	out += fmt.Sprintf("  topUsers=%v\n", o.TopUsers)
	return fmt.Sprintf("GetTopUserIdsResponse {\n%s}", out)
}
