// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package search

import (
	"encoding/json"
	"fmt"
)

// SynonymType Synonym type.
type SynonymType string

// List of SynonymType.
const (
	SYNONYM_TYPE_SYNONYM         SynonymType = "synonym"
	SYNONYM_TYPE_ONEWAYSYNONYM   SynonymType = "onewaysynonym"
	SYNONYM_TYPE_ALTCORRECTION1  SynonymType = "altcorrection1"
	SYNONYM_TYPE_ALTCORRECTION2  SynonymType = "altcorrection2"
	SYNONYM_TYPE_PLACEHOLDER     SynonymType = "placeholder"
	SYNONYM_TYPE_ONE_WAY_SYNONYM SynonymType = "oneWaySynonym"
	SYNONYM_TYPE_ALT_CORRECTION1 SynonymType = "altCorrection1"
	SYNONYM_TYPE_ALT_CORRECTION2 SynonymType = "altCorrection2"
)

// All allowed values of SynonymType enum.
var AllowedSynonymTypeEnumValues = []SynonymType{
	"synonym",
	"onewaysynonym",
	"altcorrection1",
	"altcorrection2",
	"placeholder",
	"oneWaySynonym",
	"altCorrection1",
	"altCorrection2",
}

func (v *SynonymType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return fmt.Errorf("failed to unmarshal value '%s' for enum 'SynonymType': %w", string(src), err)
	}
	enumTypeValue := SynonymType(value)
	for _, existing := range AllowedSynonymTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SynonymType", value)
}

// NewSynonymTypeFromValue returns a pointer to a valid SynonymType
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewSynonymTypeFromValue(v string) (*SynonymType, error) {
	ev := SynonymType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SynonymType: valid values are %v", v, AllowedSynonymTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v SynonymType) IsValid() bool {
	for _, existing := range AllowedSynonymTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SynonymType value.
func (v SynonymType) Ptr() *SynonymType {
	return &v
}
