// Code generated by go generate. DO NOT EDIT.

package opt

import (
	"encoding/json"
	"reflect"
)

type DecompoundedAttributesOption struct {
	value map[string][]string
}

func DecompoundedAttributes(v map[string][]string) *DecompoundedAttributesOption {
	return &DecompoundedAttributesOption{v}
}

func (o DecompoundedAttributesOption) Get() map[string][]string {
	return o.value
}

func (o DecompoundedAttributesOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.value)
}

func (o *DecompoundedAttributesOption) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		o.value = map[string][]string{}
		return nil
	}
	return json.Unmarshal(data, &o.value)
}

func (o *DecompoundedAttributesOption) Equal(o2 *DecompoundedAttributesOption) bool {
	if o2 == nil {
		return reflect.DeepEqual(o.value, map[string][]string{})
	}
	return reflect.DeepEqual(o.value, o2.value)
}

func DecompoundedAttributesEqual(o1, o2 *DecompoundedAttributesOption) bool {
	if o1 != nil {
		return o1.Equal(o2)
	}
	if o2 != nil {
		return o2.Equal(o1)
	}
	return true
}
