// Code generated by go generate. DO NOT EDIT.

package opt

import "encoding/json"

type LimitOption struct {
	value int
}

func Limit(v int) *LimitOption {
	return &LimitOption{v}
}

func (o LimitOption) Get() int {
	return o.value
}

func (o LimitOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.value)
}

func (o *LimitOption) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		o.value = 10
		return nil
	}
	return json.Unmarshal(data, &o.value)
}

func (o *LimitOption) Equal(o2 *LimitOption) bool {
	if o2 == nil {
		return o.value == 10
	}
	return o.value == o2.value
}

func LimitEqual(o1, o2 *LimitOption) bool {
	if o1 != nil {
		return o1.Equal(o2)
	}
	if o2 != nil {
		return o2.Equal(o1)
	}
	return true
}
