openapi: 3.0.2
info:
  title: Predict API
  description: API powering the Predict feature of Algolia.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://predict.{region}.algolia.com
    variables:
      region:
        enum:
          - eu
          - us
        default: eu
        description: >
          Region where your Predict data is stored and processed:
            * `eu` - Europe
            * `us` - United States.
security:
  - appId: []
    apiKey: []
tags:
  - name: models
    x-displayName: Models
    description: Manage models.
  - name: profiles
    x-displayName: Profiles
    description: Manage users' profiles.
  - name: segments
    x-displayName: Segments
    description: Manage segments.
x-tagGroups:
  - name: General
    tags:
      - profiles
      - models
      - segments
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  # ######################
  # ### Users request ###
  # ######################
  /1/users/{userID}/fetch:
    $ref: 'paths/users/fetch.yml'

  /1/users/{userID}:
    $ref: 'paths/users/delete.yml'

  /1/users:
    $ref: 'paths/users/fetchAll.yml'

  # ######################
  # ### Model request ###
  # ######################
  /1/predict/modeltypes:
    $ref: 'paths/models/getAvailableModelTypes.yml'

  /1/predict/models/{modelID}:
    $ref: 'paths/models/modelInstances.yml'

  /1/predict/models:
    $ref: 'paths/models/models.yml'

  /1/predict/models/{modelID}/metrics:
    $ref: 'paths/models/getModelMetrics.yml'

  # ########################
  # ### Segments request ###
  # ########################
  /1/segments/{segmentID}/users:
    $ref: 'paths/segments/segmentUsers.yml'

  /1/segments/{segmentID}:
    $ref: 'paths/segments/singleSegment.yml'

  /1/segments:
    $ref: 'paths/segments/allSegments.yml'
