openapi: 3.0.2
info:
  title: Predict API
  description: API powering the Predict feature of Algolia.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://predict-api-432xa6wemq-{region}.a.run.app
    variables:
      region:
        enum:
          - ue
          - ew
        default: ew
security:
  - appId: []
    apiKey: []
tags:
  - name: profiles
    x-displayName: Profiles
    description: Manage users' profiles.
x-tagGroups:
  - name: General
    tags:
      - profiles
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/users/{userID}/fetch:
    $ref: 'paths/fetchUserProfile.yml'
