openapi: 3.0.2
info:
  title: Predict API
  description: API powering the Predict feature of Algolia.
  version: 0.1.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://predict-api-oslcbws3zq-ew.a.run.app
security:
  - appId: []
    apiKey: []
tags:
  - name: predict
    description: Predict API reference.
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/users/{userID}/fetch:
    $ref: 'paths/fetchUserProfile.yml'
