post:
  tags:
    - tasks
  summary: Run a task.
  description: Run a task.
  operationId: runTask
  parameters:
    - $ref: '../../common/parameters.yml#/taskID'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../common/schemas/run.yml#/RunResponse'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
