post:
  tags:
    - tasks
  summary: Search among tasks.
  description: Search among tasks with a defined set of parameters.
  operationId: searchTasks
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../common/schemas/task.yml#/TaskSearch'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: searchTasksResponse
            type: array
            items:
              $ref: '../../common/schemas/task.yml#/Task'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
