get:
  tags:
    - tasks
  summary: Get a list of tasks.
  description: Get a list of tasks for the given query parameters, with pagination details.
  operationId: getTasks
  parameters:
    - $ref: '../../common/parameters.yml#/itemsPerPage'
    - $ref: '../../common/parameters.yml#/page'
    - $ref: '../../common/taskParameters.yml#/action'
    - $ref: '../../common/taskParameters.yml#/enabled'
    - $ref: '../../common/taskParameters.yml#/sourceID'
    - $ref: '../../common/taskParameters.yml#/destinationID'
    - $ref: '../../common/taskParameters.yml#/triggerType'
    - $ref: '../../common/taskParameters.yml#/sort'
    - $ref: '../../common/parameters.yml#/order'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: listTasksResponse
            type: object
            description: A list of tasks with pagination details.
            additionalProperties: false
            properties:
              tasks:
                type: array
                items:
                  $ref: '../../common/schemas/task.yml#/Task'
              pagination:
                $ref: '../../common/schemas/pagination.yml#/Pagination'
            required:
              - tasks
              - pagination
    '400':
      $ref: '../../../common/responses/BadRequest.yml'

post:
  tags:
    - tasks
  summary: Create a task.
  description: Create a task.
  operationId: createTask
  requestBody:
    description: ''
    content:
      application/json:
        schema:
          $ref: '../../common/schemas/task.yml#/TaskCreate'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../common/schemas/task.yml#/TaskCreateResponse'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
