post:
  tags:
    - Search
  operationId: searchForFacetValues
  x-use-read-transporter: true
  x-cacheable: true
  summary: Search for values of a given facet.
  description: Search for values of a given facet, optionally restricting the returned values to those contained in objects matching other search criteria.
  parameters:
    - $ref: '../../../common/parameters.yml#/IndexName'
    - name: facetName
      description: The facet name.
      in: path
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          title: searchForFacetValuesRequest
          type: object
          additionalProperties: false
          properties:
            params:
              $ref: '../../../common/schemas/SearchParams.yml#/paramsAsString'
            facetQuery:
              $ref: '../../common/schemas/SearchQuery.yml#/facetQuery'
            maxFacetHits:
              $ref: '../../../common/schemas/IndexSettings.yml#/maxFacetHits'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: searchForFacetValuesResponse
            type: object
            additionalProperties: false
            required:
              - facetHits
            properties:
              facetHits:
                type: array
                items:
                  type: object
                  title: facetHits
                  additionalProperties: false
                  required:
                    - value
                    - highlighted
                    - count
                  properties:
                    value:
                      description: Raw value of the facet.
                      type: string
                    highlighted:
                      $ref: '../../common/schemas/Hit.yml#/highlightedValue'
                    count:
                      description: How many objects contain this facet value. This takes into account the extra search parameters specified in the query. Like for a regular search query, the counts may not be exhaustive.
                      type: integer
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
    '402':
      $ref: '../../../common/responses/FeatureNotEnabled.yml'
    '403':
      $ref: '../../../common/responses/MethodNotAllowed.yml'
    '404':
      $ref: '../../../common/responses/IndexNotFound.yml'
