// Code generated by go generate. DO NOT EDIT.

package opt

import (
	"github.com/algolia/algoliasearch-client-go/v3/algolia/opt"
)

// ExtractClickAnalytics returns the first found ClickAnalyticsOption from the
// given variadic arguments or nil otherwise.
func ExtractClickAnalytics(opts ...interface{}) *opt.ClickAnalyticsOption {
	for _, o := range opts {
		if v, ok := o.(*opt.ClickAnalyticsOption); ok {
			return v
		}
	}
	return nil
}
