// Code generated by go generate. DO NOT EDIT.

package opt

import (
	"github.com/algolia/algoliasearch-client-go/v3/algolia/opt"
)

// ExtractRestrictIndices returns the first found RestrictIndicesOption from the
// given variadic arguments or nil otherwise.
func ExtractRestrictIndices(opts ...interface{}) *opt.RestrictIndicesOption {
	for _, o := range opts {
		if v, ok := o.(*opt.RestrictIndicesOption); ok {
			return v
		}
	}
	return nil
}
