// Code generated by go generate. DO NOT EDIT.

package opt

import (
	"github.com/algolia/algoliasearch-client-go/algolia/opt"
)

// ExtractUserData returns the first found UserDataOption from the
// given variadic arguments or nil otherwise. If multiple options are found, the
// inner maps are merged.
func ExtractUserData(opts ...interface{}) *opt.UserDataOption {
	merged := make(map[string]interface{})

	for _, o := range opts {
		if v, ok := o.(*opt.UserDataOption); ok {
			for key, value := range v.Get() {
				merged[key] = value
			}
		}
	}

	if len(merged) == 0 {
		return nil
	}

	return opt.UserData(merged)
}
