// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package abtesting

import (
	"encoding/json"
	"fmt"
)

// EmptySearchFilter Empty searches removed from the A/B test as a result of configuration settings.
type EmptySearchFilter struct {
	// Number of users removed from the A/B test.
	UsersCount *int32 `json:"usersCount,omitempty"`
	// Number of tracked searches removed from the A/B test.
	TrackedSearchesCount *int32 `json:"trackedSearchesCount,omitempty"`
}

type EmptySearchFilterOption func(f *EmptySearchFilter)

func WithEmptySearchFilterUsersCount(val int32) EmptySearchFilterOption {
	return func(f *EmptySearchFilter) {
		f.UsersCount = &val
	}
}

func WithEmptySearchFilterTrackedSearchesCount(val int32) EmptySearchFilterOption {
	return func(f *EmptySearchFilter) {
		f.TrackedSearchesCount = &val
	}
}

// NewEmptySearchFilter instantiates a new EmptySearchFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewEmptySearchFilter(opts ...EmptySearchFilterOption) *EmptySearchFilter {
	this := &EmptySearchFilter{}
	for _, opt := range opts {
		opt(this)
	}

	return this
}

// NewEmptyEmptySearchFilter return a pointer to an empty EmptySearchFilter object.
func NewEmptyEmptySearchFilter() *EmptySearchFilter {
	return &EmptySearchFilter{}
}

// GetUsersCount returns the UsersCount field value if set, zero value otherwise.
func (o *EmptySearchFilter) GetUsersCount() int32 {
	if o == nil || o.UsersCount == nil {
		var ret int32

		return ret
	}

	return *o.UsersCount
}

// GetUsersCountOk returns a tuple with the UsersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptySearchFilter) GetUsersCountOk() (*int32, bool) {
	if o == nil || o.UsersCount == nil {
		return nil, false
	}

	return o.UsersCount, true
}

// HasUsersCount returns a boolean if a field has been set.
func (o *EmptySearchFilter) HasUsersCount() bool {
	if o != nil && o.UsersCount != nil {
		return true
	}

	return false
}

// SetUsersCount gets a reference to the given int32 and assigns it to the UsersCount field.
func (o *EmptySearchFilter) SetUsersCount(v int32) *EmptySearchFilter {
	o.UsersCount = &v

	return o
}

// GetTrackedSearchesCount returns the TrackedSearchesCount field value if set, zero value otherwise.
func (o *EmptySearchFilter) GetTrackedSearchesCount() int32 {
	if o == nil || o.TrackedSearchesCount == nil {
		var ret int32

		return ret
	}

	return *o.TrackedSearchesCount
}

// GetTrackedSearchesCountOk returns a tuple with the TrackedSearchesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptySearchFilter) GetTrackedSearchesCountOk() (*int32, bool) {
	if o == nil || o.TrackedSearchesCount == nil {
		return nil, false
	}

	return o.TrackedSearchesCount, true
}

// HasTrackedSearchesCount returns a boolean if a field has been set.
func (o *EmptySearchFilter) HasTrackedSearchesCount() bool {
	if o != nil && o.TrackedSearchesCount != nil {
		return true
	}

	return false
}

// SetTrackedSearchesCount gets a reference to the given int32 and assigns it to the TrackedSearchesCount field.
func (o *EmptySearchFilter) SetTrackedSearchesCount(v int32) *EmptySearchFilter {
	o.TrackedSearchesCount = &v

	return o
}

func (o EmptySearchFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if o.UsersCount != nil {
		toSerialize["usersCount"] = o.UsersCount
	}

	if o.TrackedSearchesCount != nil {
		toSerialize["trackedSearchesCount"] = o.TrackedSearchesCount
	}

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal EmptySearchFilter: %w", err)
	}

	return serialized, nil
}

func (o EmptySearchFilter) String() string {
	out := ""
	out += fmt.Sprintf("  usersCount=%v\n", o.UsersCount)
	out += fmt.Sprintf("  trackedSearchesCount=%v\n", o.TrackedSearchesCount)

	return fmt.Sprintf("EmptySearchFilter {\n%s}", out)
}
