name: Restore artifacts

description: |
  When no input is given, artifacts are restored in the current directory, under their artifact `name`.

  This composite restore all of our artifacts, at their right path.

inputs:
  type:
    description: Type of artifacts to restore (`all` | `specs` | `js_utils`)
    required: false
  php:
    description: Whether this job ran or not
    required: false
  java:
    description: Whether this job ran or not
    required: false
  javascript:
    description: Whether this job ran or not
    required: false

runs:
  using: composite
  steps:
    # Bundled specs
    - name: specs
      if: ${{ inputs.type == 'all' || inputs.type == 'specs' }}
      uses: actions/download-artifact@v3
      with:
        name: specs
        path: specs/bundled/

    # JavaScript utils
    - name: client-javascript-utils-client-common
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-client-common
        path: clients/algoliasearch-client-javascript/packages/client-common/

    - name: client-javascript-utils-requester-browser-xhr
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-requester-browser-xhr
        path: clients/algoliasearch-client-javascript/packages/requester-browser-xhr/

    - name: client-javascript-utils-requester-node-http
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-requester-node-http
        path: clients/algoliasearch-client-javascript/packages/requester-node-http/

    - name: client-javascript-utils-requester-fetch
      if: ${{ (inputs.javascript == 'true' && inputs.type == 'all') || inputs.type == 'js_utils' }}
      uses: actions/download-artifact@v3
      with:
        name: client-javascript-utils-requester-fetch
        path: clients/algoliasearch-client-javascript/packages/requester-fetch/

    # JavaScript
    - name: Download clients-javascript artifact
      if: ${{ inputs.javascript == 'true' && inputs.type == 'all' }}
      uses: actions/download-artifact@v3
      with:
        name: clients-javascript

    - name: Unzip clients-javascript artifact
      if: ${{ inputs.javascript == 'true' && inputs.type == 'all' }}
      shell: bash
      run: |
        rm -rf clients/algoliasearch-client-javascript
        rm -rf tests/output/javascript/src/client || true
        rm -rf tests/output/javascript/src/methods || true
        unzip -q -o clients-javascript.zip && rm clients-javascript.zip

    # PHP
    - name: Download clients-php artifact
      if: ${{ inputs.php == 'true' && inputs.type == 'all' }}
      uses: actions/download-artifact@v3
      with:
        name: clients-php

    - name: Unzip clients-php artifact
      if: ${{ inputs.php == 'true' && inputs.type == 'all' }}
      shell: bash
      run: |
        rm -rf clients/algoliasearch-client-php
        rm -rf tests/output/php/src/client || true
        rm -rf tests/output/php/src/methods || true
        unzip -q -o clients-php.zip && rm clients-php.zip

    # Java
    - name: Download clients-java artifact
      if: ${{ inputs.java == 'true' && inputs.type == 'all' }}
      uses: actions/download-artifact@v3
      with:
        name: clients-java

    - name: Unzip clients-java artifact
      if: ${{ inputs.java == 'true' && inputs.type == 'all' }}
      shell: bash
      run: |
        rm -rf clients/algoliasearch-client-java-2
        rm -rf tests/output/java/src/test/java/com/algolia/client || true
        rm -rf tests/output/java/src/test/java/com/algolia/methods || true
        unzip -q -o clients-java.zip && rm clients-java.zip
