// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package personalization

import (
	"github.com/algolia/algoliasearch-client-go/v4/algolia/transport"
)

var allowedRegions = [...]string{"eu", "us"}

type Region string

const (
	EU Region = "eu"
	US Region = "us"
)

// PersonalizationConfiguration stores the configuration of the API client.
type PersonalizationConfiguration struct {
	transport.Configuration

	Region Region
}
