openapi: 3.0.2
info:
  title: Insights API
  description: API powering the Insights feature of Algolia.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://insights.{region}.algolia.io
    variables:
      region:
        enum:
          - us
          - de
        default: us
  - url: https://insights.algolia.io
security:
  - appId: []
    apiKey: []
tags:
  - name: events
    x-displayName: Events
    description: Events operations.
x-tagGroups:
  - name: General
    tags:
      - events
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/events:
    $ref: 'paths/pushEvents.yml'
