openapi: 3.0.2
info:
  title: A/B Testing API
  description: API powering the A/B Testing feature of Algolia.
  version: 0.1.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://analytics.{region}.algolia.com
    variables:
      region:
        enum:
          - us
          - de
        default: us
  - url: https://analytics.algolia.com
security:
  - appId: []
    apiKey: []
tags:
  - name: abtesting
    description: abtesting API reference.
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /2/abtests:
    $ref: 'paths/abtests.yml'
  /2/abtests/{id}:
    $ref: 'paths/abtest.yml'
  /2/abtests/{id}/stop:
    $ref: 'paths/stopABTest.yml'
