// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package abtestingV3

import (
	"encoding/json"
	"fmt"
)

// FeatureSettings Feature-specific settings captured for a variant.
type FeatureSettings struct {
	// Name of the feature the settings belong to.
	Name string `json:"name"`
	// Feature settings payload. The shape depends on the feature.
	Settings any `json:"settings"`
}

// NewFeatureSettings instantiates a new FeatureSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewFeatureSettings(name string, settings any) *FeatureSettings {
	this := &FeatureSettings{}
	this.Name = name
	this.Settings = settings

	return this
}

// NewEmptyFeatureSettings return a pointer to an empty FeatureSettings object.
func NewEmptyFeatureSettings() *FeatureSettings {
	return &FeatureSettings{}
}

// GetName returns the Name field value.
func (o *FeatureSettings) GetName() string {
	if o == nil {
		var ret string

		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FeatureSettings) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return &o.Name, true
}

// SetName sets field value.
func (o *FeatureSettings) SetName(v string) *FeatureSettings {
	o.Name = v

	return o
}

// GetSettings returns the Settings field value.
// If the value is explicit nil, the zero value for any will be returned.
func (o *FeatureSettings) GetSettings() any {
	if o == nil {
		var ret any

		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned.
func (o *FeatureSettings) GetSettingsOk() (*any, bool) {
	if o == nil || o.Settings == nil {
		return nil, false
	}

	return &o.Settings, true
}

// SetSettings sets field value.
func (o *FeatureSettings) SetSettings(v any) *FeatureSettings {
	o.Settings = v

	return o
}

func (o FeatureSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}

	toSerialize["name"] = o.Name
	if o.Settings != nil {
		toSerialize["settings"] = o.Settings
	}

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal FeatureSettings: %w", err)
	}

	return serialized, nil
}

func (o FeatureSettings) String() string {
	out := ""
	out += fmt.Sprintf("  name=%v\n", o.Name)
	out += fmt.Sprintf("  settings=%v\n", o.Settings)

	return fmt.Sprintf("FeatureSettings {\n%s}", out)
}
