// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package abtestingV3

import (
	"encoding/json"
	"fmt"
)

// Status A/B test status.  - `active`. The A/B test is live and search traffic is split between the two variants. - `stopped`. You stopped the A/B test. The A/B test data is still available for analysis. - `expired`. The A/B test was automatically stopped after reaching its end date. - `failed`. Creating the A/B test failed.
type Status string

// List of Status.
const (
	STATUS_ACTIVE  Status = "active"
	STATUS_STOPPED Status = "stopped"
	STATUS_EXPIRED Status = "expired"
	STATUS_FAILED  Status = "failed"
)

// All allowed values of Status enum.
var AllowedStatusEnumValues = []Status{
	"active",
	"stopped",
	"expired",
	"failed",
}

// NewStatusFromValue returns a pointer to a valid Status.
// for the value passed as argument, or an error if the value passed is not allowed by the enum.
func NewStatusFromValue(v string) (*Status, error) {
	ev := Status(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Status: valid values are %v", v, AllowedStatusEnumValues)
	}
}

func (v *Status) UnmarshalJSON(src []byte) error {
	var value string

	err := json.Unmarshal(src, &value)
	if err != nil {
		return fmt.Errorf("failed to unmarshal value '%s' for enum 'Status': %w", string(src), err)
	}

	enumTypeValue := Status(value)
	for _, existing := range AllowedStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue

			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Status", value)
}

// IsValid return true if the value is valid for the enum, false otherwise.
func (v Status) IsValid() bool {
	for _, existing := range AllowedStatusEnumValues {
		if existing == v {
			return true
		}
	}

	return false
}

// Ptr returns reference to Status value.
func (v Status) Ptr() *Status {
	return &v
}
