// File generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation.
package ingestion

import (
	"encoding/json"
	"fmt"
)

// AuthAPIKey Credentials for authenticating with an API key.
type AuthAPIKey struct {
	// API key. This field is `null` in the API response.
	Key string `json:"key"`
}

// NewAuthAPIKey instantiates a new AuthAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewAuthAPIKey(key string) *AuthAPIKey {
	this := &AuthAPIKey{}
	this.Key = key
	return this
}

// NewEmptyAuthAPIKey return a pointer to an empty AuthAPIKey object.
func NewEmptyAuthAPIKey() *AuthAPIKey {
	return &AuthAPIKey{}
}

// GetKey returns the Key field value.
func (o *AuthAPIKey) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *AuthAPIKey) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value.
func (o *AuthAPIKey) SetKey(v string) *AuthAPIKey {
	o.Key = v
	return o
}

func (o AuthAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if true {
		toSerialize["key"] = o.Key
	}
	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal AuthAPIKey: %w", err)
	}

	return serialized, nil
}

func (o AuthAPIKey) String() string {
	out := ""
	out += fmt.Sprintf("  key=%v\n", o.Key)
	return fmt.Sprintf("AuthAPIKey {\n%s}", out)
}

type NullableAuthAPIKey struct {
	value *AuthAPIKey
	isSet bool
}

func (v NullableAuthAPIKey) Get() *AuthAPIKey {
	return v.value
}

func (v *NullableAuthAPIKey) Set(val *AuthAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthAPIKey(val *AuthAPIKey) *NullableAuthAPIKey {
	return &NullableAuthAPIKey{value: val, isSet: true}
}

func (v NullableAuthAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value) //nolint:wrapcheck
}

func (v *NullableAuthAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value) //nolint:wrapcheck
}
