// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package ingestion

import (
	"encoding/json"
	"fmt"
)

// RunListResponse struct for RunListResponse
type RunListResponse struct {
	Runs       []Run      `json:"runs"`
	Pagination Pagination `json:"pagination"`
}

// NewRunListResponse instantiates a new RunListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunListResponse(runs []Run, pagination Pagination) *RunListResponse {
	this := &RunListResponse{}
	this.Runs = runs
	this.Pagination = pagination
	return this
}

// NewRunListResponseWithDefaults instantiates a new RunListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunListResponseWithDefaults() *RunListResponse {
	this := &RunListResponse{}
	return this
}

// GetRuns returns the Runs field value
func (o *RunListResponse) GetRuns() []Run {
	if o == nil {
		var ret []Run
		return ret
	}

	return o.Runs
}

// GetRunsOk returns a tuple with the Runs field value
// and a boolean to check if the value has been set.
func (o *RunListResponse) GetRunsOk() ([]Run, bool) {
	if o == nil {
		return nil, false
	}
	return o.Runs, true
}

// SetRuns sets field value
func (o *RunListResponse) SetRuns(v []Run) {
	o.Runs = v
}

// GetPagination returns the Pagination field value
func (o *RunListResponse) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *RunListResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *RunListResponse) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o RunListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if true {
		toSerialize["runs"] = o.Runs
	}
	if true {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

func (o RunListResponse) String() string {
	out := "RunListResponse {\n"
	out += fmt.Sprintf("  runs=%v\n", o.Runs)
	out += fmt.Sprintf("  pagination=%v\n", o.Pagination)
	out += "}"
	return out
}

type NullableRunListResponse struct {
	value *RunListResponse
	isSet bool
}

func (v NullableRunListResponse) Get() *RunListResponse {
	return v.value
}

func (v *NullableRunListResponse) Set(val *RunListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRunListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRunListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunListResponse(val *RunListResponse) *NullableRunListResponse {
	return &NullableRunListResponse{value: val, isSet: true}
}

func (v NullableRunListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
