// File generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation.
package ingestion

import (
	"encoding/json"
	"fmt"
)

// Authentication An authentication is used to login into a Source or a Destination.
type Authentication struct {
	// The authentication UUID.
	AuthenticationID string             `json:"authenticationID"`
	Type             AuthenticationType `json:"type"`
	// An human readable name describing the object.
	Name     string    `json:"name"`
	Platform *Platform `json:"platform,omitempty"`
	Input    AuthInput `json:"input"`
	// Date of creation (RFC3339 format).
	CreatedAt string `json:"createdAt"`
	// Date of last update (RFC3339 format).
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type AuthenticationOption func(f *Authentication)

func WithAuthenticationPlatform(val Platform) AuthenticationOption {
	return func(f *Authentication) {
		f.Platform = &val
	}
}

func WithAuthenticationUpdatedAt(val string) AuthenticationOption {
	return func(f *Authentication) {
		f.UpdatedAt = &val
	}
}

// NewAuthentication instantiates a new Authentication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewAuthentication(authenticationID string, type_ AuthenticationType, name string, input AuthInput, createdAt string, opts ...AuthenticationOption) *Authentication {
	this := &Authentication{}
	this.AuthenticationID = authenticationID
	this.Type = type_
	this.Name = name
	this.Input = input
	this.CreatedAt = createdAt
	for _, opt := range opts {
		opt(this)
	}
	return this
}

// NewEmptyAuthentication return a pointer to an empty Authentication object.
func NewEmptyAuthentication() *Authentication {
	return &Authentication{}
}

// GetAuthenticationID returns the AuthenticationID field value.
func (o *Authentication) GetAuthenticationID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationID
}

// GetAuthenticationIDOk returns a tuple with the AuthenticationID field value
// and a boolean to check if the value has been set.
func (o *Authentication) GetAuthenticationIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationID, true
}

// SetAuthenticationID sets field value.
func (o *Authentication) SetAuthenticationID(v string) *Authentication {
	o.AuthenticationID = v
	return o
}

// GetType returns the Type field value.
func (o *Authentication) GetType() AuthenticationType {
	if o == nil {
		var ret AuthenticationType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Authentication) GetTypeOk() (*AuthenticationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value.
func (o *Authentication) SetType(v AuthenticationType) *Authentication {
	o.Type = v
	return o
}

// GetName returns the Name field value.
func (o *Authentication) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Authentication) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value.
func (o *Authentication) SetName(v string) *Authentication {
	o.Name = v
	return o
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *Authentication) GetPlatform() Platform {
	if o == nil || o.Platform == nil {
		var ret Platform
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Authentication) GetPlatformOk() (*Platform, bool) {
	if o == nil || o.Platform == nil {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *Authentication) HasPlatform() bool {
	if o != nil && o.Platform != nil {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given Platform and assigns it to the Platform field.
func (o *Authentication) SetPlatform(v Platform) *Authentication {
	o.Platform = &v
	return o
}

// GetInput returns the Input field value.
func (o *Authentication) GetInput() AuthInput {
	if o == nil {
		var ret AuthInput
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *Authentication) GetInputOk() (*AuthInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value.
func (o *Authentication) SetInput(v *AuthInput) *Authentication {
	o.Input = *v
	return o
}

// GetCreatedAt returns the CreatedAt field value.
func (o *Authentication) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Authentication) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value.
func (o *Authentication) SetCreatedAt(v string) *Authentication {
	o.CreatedAt = v
	return o
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Authentication) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Authentication) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Authentication) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Authentication) SetUpdatedAt(v string) *Authentication {
	o.UpdatedAt = &v
	return o
}

func (o Authentication) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if true {
		toSerialize["authenticationID"] = o.AuthenticationID
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Platform != nil {
		toSerialize["platform"] = o.Platform
	}
	if true {
		toSerialize["input"] = o.Input
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal Authentication: %w", err)
	}

	return serialized, nil
}

func (o Authentication) String() string {
	out := ""
	out += fmt.Sprintf("  authenticationID=%v\n", o.AuthenticationID)
	out += fmt.Sprintf("  type=%v\n", o.Type)
	out += fmt.Sprintf("  name=%v\n", o.Name)
	out += fmt.Sprintf("  platform=%v\n", o.Platform)
	out += fmt.Sprintf("  input=%v\n", o.Input)
	out += fmt.Sprintf("  createdAt=%v\n", o.CreatedAt)
	out += fmt.Sprintf("  updatedAt=%v\n", o.UpdatedAt)
	return fmt.Sprintf("Authentication {\n%s}", out)
}

type NullableAuthentication struct {
	value *Authentication
	isSet bool
}

func (v NullableAuthentication) Get() *Authentication {
	return v.value
}

func (v *NullableAuthentication) Set(val *Authentication) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthentication) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthentication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthentication(val *Authentication) *NullableAuthentication {
	return &NullableAuthentication{value: val, isSet: true}
}

func (v NullableAuthentication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value) //nolint:wrapcheck
}

func (v *NullableAuthentication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value) //nolint:wrapcheck
}
