// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package ingestion

import (
	"encoding/json"
	"fmt"
)

// DestinationCreate The payload when creating a destination.
type DestinationCreate struct {
	Type DestinationType `json:"type"`
	// An human readable name describing the object.
	Name  string           `json:"name"`
	Input DestinationInput `json:"input"`
	// The authentication UUID.
	AuthenticationID *string `json:"authenticationID,omitempty"`
}

type DestinationCreateOption func(f *DestinationCreate)

func WithDestinationCreateAuthenticationID(val string) DestinationCreateOption {
	return func(f *DestinationCreate) {
		f.AuthenticationID = &val
	}
}

// NewDestinationCreate instantiates a new DestinationCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationCreate(type_ DestinationType, name string, input DestinationInput, opts ...DestinationCreateOption) *DestinationCreate {
	this := &DestinationCreate{}
	this.Type = type_
	this.Name = name
	this.Input = input
	for _, opt := range opts {
		opt(this)
	}
	return this
}

// NewDestinationCreateWithDefaults instantiates a new DestinationCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationCreateWithDefaults() *DestinationCreate {
	this := &DestinationCreate{}
	return this
}

// GetType returns the Type field value
func (o *DestinationCreate) GetType() DestinationType {
	if o == nil {
		var ret DestinationType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DestinationCreate) GetTypeOk() (*DestinationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DestinationCreate) SetType(v DestinationType) {
	o.Type = v
}

// GetName returns the Name field value
func (o *DestinationCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DestinationCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DestinationCreate) SetName(v string) {
	o.Name = v
}

// GetInput returns the Input field value
func (o *DestinationCreate) GetInput() DestinationInput {
	if o == nil {
		var ret DestinationInput
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *DestinationCreate) GetInputOk() (*DestinationInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *DestinationCreate) SetInput(v DestinationInput) {
	o.Input = v
}

// GetAuthenticationID returns the AuthenticationID field value if set, zero value otherwise.
func (o *DestinationCreate) GetAuthenticationID() string {
	if o == nil || o.AuthenticationID == nil {
		var ret string
		return ret
	}
	return *o.AuthenticationID
}

// GetAuthenticationIDOk returns a tuple with the AuthenticationID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationCreate) GetAuthenticationIDOk() (*string, bool) {
	if o == nil || o.AuthenticationID == nil {
		return nil, false
	}
	return o.AuthenticationID, true
}

// HasAuthenticationID returns a boolean if a field has been set.
func (o *DestinationCreate) HasAuthenticationID() bool {
	if o != nil && o.AuthenticationID != nil {
		return true
	}

	return false
}

// SetAuthenticationID gets a reference to the given string and assigns it to the AuthenticationID field.
func (o *DestinationCreate) SetAuthenticationID(v string) {
	o.AuthenticationID = &v
}

func (o DestinationCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["input"] = o.Input
	}
	if o.AuthenticationID != nil {
		toSerialize["authenticationID"] = o.AuthenticationID
	}
	return json.Marshal(toSerialize)
}

func (o DestinationCreate) String() string {
	out := "DestinationCreate {\n"
	out += fmt.Sprintf("  type=%v\n", o.Type)
	out += fmt.Sprintf("  name=%v\n", o.Name)
	out += fmt.Sprintf("  input=%v\n", o.Input)
	out += fmt.Sprintf("  authenticationID=%v\n", o.AuthenticationID)
	out += "}"
	return out
}

type NullableDestinationCreate struct {
	value *DestinationCreate
	isSet bool
}

func (v NullableDestinationCreate) Get() *DestinationCreate {
	return v.value
}

func (v *NullableDestinationCreate) Set(val *DestinationCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationCreate(val *DestinationCreate) *NullableDestinationCreate {
	return &NullableDestinationCreate{value: val, isSet: true}
}

func (v NullableDestinationCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
