// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package ingestion

import (
	"encoding/json"
	"fmt"
)

// DestinationSortKeys Used to sort the Destination list endpoint.
type DestinationSortKeys string

// List of destinationSortKeys
const (
	DESTINATIONSORTKEYS_NAME       DestinationSortKeys = "name"
	DESTINATIONSORTKEYS_TYPE       DestinationSortKeys = "type"
	DESTINATIONSORTKEYS_UPDATED_AT DestinationSortKeys = "updatedAt"
	DESTINATIONSORTKEYS_CREATED_AT DestinationSortKeys = "createdAt"
)

// All allowed values of DestinationSortKeys enum
var AllowedDestinationSortKeysEnumValues = []DestinationSortKeys{
	"name",
	"type",
	"updatedAt",
	"createdAt",
}

func (v *DestinationSortKeys) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DestinationSortKeys(value)
	for _, existing := range AllowedDestinationSortKeysEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DestinationSortKeys", value)
}

// NewDestinationSortKeysFromValue returns a pointer to a valid DestinationSortKeys
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDestinationSortKeysFromValue(v string) (*DestinationSortKeys, error) {
	ev := DestinationSortKeys(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DestinationSortKeys: valid values are %v", v, AllowedDestinationSortKeysEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DestinationSortKeys) IsValid() bool {
	for _, existing := range AllowedDestinationSortKeysEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to destinationSortKeys value
func (v DestinationSortKeys) Ptr() *DestinationSortKeys {
	return &v
}

type NullableDestinationSortKeys struct {
	value *DestinationSortKeys
	isSet bool
}

func (v NullableDestinationSortKeys) Get() *DestinationSortKeys {
	return v.value
}

func (v *NullableDestinationSortKeys) Set(val *DestinationSortKeys) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationSortKeys) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationSortKeys) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationSortKeys(val *DestinationSortKeys) *NullableDestinationSortKeys {
	return &NullableDestinationSortKeys{value: val, isSet: true}
}

func (v NullableDestinationSortKeys) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationSortKeys) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
