openapi: 3.0.2
info:
  title: Event & Records Connection API
  description: API powering the ingestion of Events and Records.
  version: 1.0.0
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://data.{region}.algolia.com
    variables:
      region:
        default: us
        enum:
          - us
          - de
security:
  - appId: []
    apiKey: []
tags:
  - name: jobs
    x-displayName: Jobs
    description: Manage jobs.
x-tagGroups:
  - name: General
    tags:
      - jobs
paths:
  # ######################
  # ### Custom request ###
  # ######################
  /1{path}:
    $ref: '../common/paths/customRequest.yml'

  /1/ingest/url:
    $ref: 'paths/ingest/postUrl.yml'
