pathAuthenticationID:
  name: authenticationID
  in: path
  required: true
  description: The authentication UUID.
  schema:
    $ref: './schemas/common.yml#/authenticationID'

pathDestinationID:
  name: destinationID
  in: path
  required: true
  description: The destination UUID.
  schema:
    $ref: './schemas/common.yml#/destinationID'

pathSourceID:
  name: sourceID
  in: path
  required: true
  description: The source UUID.
  schema:
    $ref: './schemas/common.yml#/sourceID'

pathTaskID:
  name: taskID
  in: path
  required: true
  description: The task UUID.
  schema:
    $ref: './schemas/common.yml#/taskID'

pathRunID:
  name: runID
  in: path
  required: true
  description: The run UUID.
  schema:
    $ref: './schemas/common.yml#/runID'

pathEventID:
  name: eventID
  in: path
  required: true
  description: The event UUID.
  schema:
    $ref: './schemas/common.yml#/eventID'

itemsPerPage:
  name: itemsPerPage
  in: query
  description: The number of items per page to return.
  required: false
  schema:
    type: integer

page:
  name: page
  in: query
  description: The page number to fetch, starting at 1.
  required: false
  schema:
    type: integer

order:
  name: order
  in: query
  description: The order of the returned list.
  required: false
  schema:
    $ref: '#/orderKeys'

orderKeys:
  type: string
  description: Used to order a sorted request.
  enum: [asc, desc]
