userID:
  name: userID
  in: path
  required: true
  schema:
    type: string
  description: User ID for authenticated users or cookie ID for non-authenticated repeated users (visitors).

segmentID:
  name: segmentID
  in: path
  required: true
  schema:
    type: string
  description: The ID of the Segment to fetch.

type:
  name: type
  in: query
  schema:
    $ref: '../responses/Segment.yml#/segmentType'
  description: The type of segments to fetch.

modelID:
  name: modelID
  in: path
  required: true
  schema:
    type: string
  description: The ID of the model to retrieve.
