// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package analytics

import (
	"encoding/json"
	"fmt"
)

// FilterDefinition struct for FilterDefinition.
type FilterDefinition struct {
	// Domain the field belongs to.
	Domain *string `json:"domain,omitempty"`
	// Field to filter on. With no `operator`, the field must be boolean.
	Kind string `json:"kind"`
	// Comparison operator applied to a filter field, one of: `=`, `!=`, `>`, `<`, `>=`, `<=`, `IN`, `TAG_TREE`, `CONTAINS`, `STARTS_WITH`, `CONTAINS_PREFIX`. Requires a `parameter` to carry the operand.
	Operator  *string             `json:"operator,omitempty"`
	Parameter *ParameterReference `json:"parameter,omitempty"`
}

type FilterDefinitionOption func(f *FilterDefinition)

func WithFilterDefinitionDomain(val string) FilterDefinitionOption {
	return func(f *FilterDefinition) {
		f.Domain = &val
	}
}

func WithFilterDefinitionOperator(val string) FilterDefinitionOption {
	return func(f *FilterDefinition) {
		f.Operator = &val
	}
}

func WithFilterDefinitionParameter(val ParameterReference) FilterDefinitionOption {
	return func(f *FilterDefinition) {
		f.Parameter = &val
	}
}

// NewFilterDefinition instantiates a new FilterDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewFilterDefinition(kind string, opts ...FilterDefinitionOption) *FilterDefinition {
	this := &FilterDefinition{}

	this.Kind = kind
	for _, opt := range opts {
		opt(this)
	}

	return this
}

// NewEmptyFilterDefinition return a pointer to an empty FilterDefinition object.
func NewEmptyFilterDefinition() *FilterDefinition {
	return &FilterDefinition{}
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *FilterDefinition) GetDomain() string {
	if o == nil || o.Domain == nil {
		var ret string

		return ret
	}

	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterDefinition) GetDomainOk() (*string, bool) {
	if o == nil || o.Domain == nil {
		return nil, false
	}

	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *FilterDefinition) HasDomain() bool {
	if o != nil && o.Domain != nil {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *FilterDefinition) SetDomain(v string) *FilterDefinition {
	o.Domain = &v

	return o
}

// GetKind returns the Kind field value.
func (o *FilterDefinition) GetKind() string {
	if o == nil {
		var ret string

		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *FilterDefinition) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}

	return &o.Kind, true
}

// SetKind sets field value.
func (o *FilterDefinition) SetKind(v string) *FilterDefinition {
	o.Kind = v

	return o
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *FilterDefinition) GetOperator() string {
	if o == nil || o.Operator == nil {
		var ret string

		return ret
	}

	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterDefinition) GetOperatorOk() (*string, bool) {
	if o == nil || o.Operator == nil {
		return nil, false
	}

	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *FilterDefinition) HasOperator() bool {
	if o != nil && o.Operator != nil {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *FilterDefinition) SetOperator(v string) *FilterDefinition {
	o.Operator = &v

	return o
}

// GetParameter returns the Parameter field value if set, zero value otherwise.
func (o *FilterDefinition) GetParameter() ParameterReference {
	if o == nil || o.Parameter == nil {
		var ret ParameterReference

		return ret
	}

	return *o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilterDefinition) GetParameterOk() (*ParameterReference, bool) {
	if o == nil || o.Parameter == nil {
		return nil, false
	}

	return o.Parameter, true
}

// HasParameter returns a boolean if a field has been set.
func (o *FilterDefinition) HasParameter() bool {
	if o != nil && o.Parameter != nil {
		return true
	}

	return false
}

// SetParameter gets a reference to the given ParameterReference and assigns it to the Parameter field.
func (o *FilterDefinition) SetParameter(v *ParameterReference) *FilterDefinition {
	o.Parameter = v

	return o
}

func (o FilterDefinition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}

	toSerialize["kind"] = o.Kind
	if o.Operator != nil {
		toSerialize["operator"] = o.Operator
	}

	if o.Parameter != nil {
		toSerialize["parameter"] = o.Parameter
	}

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal FilterDefinition: %w", err)
	}

	return serialized, nil
}

func (o FilterDefinition) String() string {
	out := ""
	out += fmt.Sprintf("  domain=%v\n", o.Domain)
	out += fmt.Sprintf("  kind=%v\n", o.Kind)
	out += fmt.Sprintf("  operator=%v\n", o.Operator)
	out += fmt.Sprintf("  parameter=%v\n", o.Parameter)

	return fmt.Sprintf("FilterDefinition {\n%s}", out)
}
