// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.
package analytics

import (
	"encoding/json"
	"fmt"
)

// GetSearchesNoClicksResponse struct for GetSearchesNoClicksResponse.
type GetSearchesNoClicksResponse struct {
	// Searches without any clicks.
	Searches []DailySearchesNoClicks `json:"searches"`
}

// NewGetSearchesNoClicksResponse instantiates a new GetSearchesNoClicksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed.
func NewGetSearchesNoClicksResponse(searches []DailySearchesNoClicks) *GetSearchesNoClicksResponse {
	this := &GetSearchesNoClicksResponse{}
	this.Searches = searches

	return this
}

// NewEmptyGetSearchesNoClicksResponse return a pointer to an empty GetSearchesNoClicksResponse object.
func NewEmptyGetSearchesNoClicksResponse() *GetSearchesNoClicksResponse {
	return &GetSearchesNoClicksResponse{}
}

// GetSearches returns the Searches field value.
func (o *GetSearchesNoClicksResponse) GetSearches() []DailySearchesNoClicks {
	if o == nil {
		var ret []DailySearchesNoClicks

		return ret
	}

	return o.Searches
}

// GetSearchesOk returns a tuple with the Searches field value
// and a boolean to check if the value has been set.
func (o *GetSearchesNoClicksResponse) GetSearchesOk() ([]DailySearchesNoClicks, bool) {
	if o == nil {
		return nil, false
	}

	return o.Searches, true
}

// SetSearches sets field value.
func (o *GetSearchesNoClicksResponse) SetSearches(v []DailySearchesNoClicks) *GetSearchesNoClicksResponse {
	o.Searches = v

	return o
}

func (o GetSearchesNoClicksResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	toSerialize["searches"] = o.Searches

	serialized, err := json.Marshal(toSerialize)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal GetSearchesNoClicksResponse: %w", err)
	}

	return serialized, nil
}

func (o GetSearchesNoClicksResponse) String() string {
	out := ""
	out += fmt.Sprintf("  searches=%v\n", o.Searches)

	return fmt.Sprintf("GetSearchesNoClicksResponse {\n%s}", out)
}
