get:
  tags:
    - sources
  summary: Get a list of sources.
  description: Get a list of sources.
  operationId: getSources
  parameters:
    - $ref: '../../common/parameters.yml#/itemsPerPage'
    - $ref: '../../common/parameters.yml#/page'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: listSourcesResponse
            type: object
            additionalProperties: false
            properties:
              sources:
                type: array
                items:
                  $ref: '../../common/schemas/source.yml#/Source'
              pagination:
                $ref: '../../common/schemas/pagination.yml#/Pagination'
            required:
              - sources
              - pagination
    '400':
      $ref: '../../../common/responses/BadRequest.yml'

post:
  tags:
    - sources
  summary: Create a source.
  description: Create a source.
  operationId: createSource
  requestBody:
    description: ''
    content:
      application/json:
        schema:
          $ref: '../../common/schemas/source.yml#/SourceCreate'
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../common/schemas/source.yml#/SourceCreateResponse'
    '400':
      $ref: '../../../common/responses/BadRequest.yml'
