get:
  operationId: getSettings
  description: Retrieve settings of a given indexName.
  summary: Retrieve settings of a given indexName.
  parameters:
    - $ref: '../../../common/parameters.yml#/IndexName'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../common/schemas/IndexSettings.yml#/indexSettings'
    '400':
      $ref: ../../../common/responses/BadRequest.yml
    '402':
      $ref: ../../../common/responses/FeatureNotEnabled.yml
    '403':
      $ref: ../../../common/responses/MethodNotAllowed.yml
    '404':
      $ref: ../../../common/responses/IndexNotFound.yml

put:
  operationId: setSettings
  description: Update settings of a given indexName. Only specified settings are overridden; unspecified settings are left unchanged. Specifying null for a setting resets it to its default value.
  summary: Update settings of a given indexName.
  parameters:
    - $ref: '../../../common/parameters.yml#/IndexName'
    - $ref: '../../../common/parameters.yml#/ForwardToReplicas'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../../common/schemas/IndexSettings.yml#/indexSettings'
  responses:
    '200':
      $ref: ../../../common/responses/UpdatedAt.yml
    '400':
      $ref: ../../../common/responses/BadRequest.yml
    '402':
      $ref: ../../../common/responses/FeatureNotEnabled.yml
    '403':
      $ref: ../../../common/responses/MethodNotAllowed.yml
    '404':
      $ref: ../../../common/responses/IndexNotFound.yml
