name: Codegen cleanup

on:
  pull_request:
    types: [closed]

env:
  CACHE_VERSION: '9'

jobs:
  codegen:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Clean previously generated branch
        run: yarn workspace scripts cleanGeneratedBranch ${{ github.head_ref }}
