name: Process release

on:
  issues:
    types:
      - closed

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    if: "startsWith(github.event.issue.title, 'chore: release')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_RELEASE_BOT }}
          ref: main_test

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          workflow_name: process-release

      - run: yarn workspace scripts processRelease
        env:
          EVENT_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE_BOT }}
          VERSION_TAG_ON_RELEASE: $${{ secrets.VERSION_TAG_ON_RELEASE }}
