name: Release version

on:
  push:
    branches:
      - next

jobs:
  release:
    name: Release tag
    runs-on: ubuntu-20.04
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ALGOLIA_BOT_TOKEN }}
      - name: Extract version
        id: extract-version
        run: |
          version="v$(echo "${{ github.event.head_commit.message }}" | grep -oP 'release \K[\d.]+[-\w.]*')"
          echo "Extracted version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create git tag
        if: ${{ steps.extract-version.outputs.version != '' }}
        run: |
          git config --local user.email "accounts+algolia-api-client-bot@algolia.com"
          git config --local user.name "algolia-bot"
          git tag -a "${{ steps.extract-version.outputs.version }}" -m "Release $version"
          git push origin "${{ steps.extract-version.outputs.version }}"
