name: Renovate

on:
  schedule:
    - cron: '0 14 * * 5' # At 14:00 on Friday.

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Automatic Branch
        uses: bodinsamuel/renovate-automatic-branch@v1
        with:
          github-token: ${{ secrets.ALGOLIA_BOT_TOKEN }}
          repo-owner: algolia
          repo-name: api-clients-automation
