name: Renovate

on:
  schedule:
    - cron: '0 14 * * 5'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          type: minimal

      - run: yarn workspace scripts renovateWeeklyPR
        env:
          GITHUB_TOKEN: ${{ secrets.ALGOLIA_BOT_TOKEN }}
