name: Scheduled Release

on:
  schedule:
    - cron: '30 6 * * 2'

jobs:
  release:
    name: Scheduled Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          type: minimal

      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.ALGOLIA_BOT_TOKEN }}
