openapi: 3.0.2
info:
  title: Ingestion API
  description: API powering the Data Ingestion connectors of Algolia.
  version: '1.0'
components:
  securitySchemes:
    appId:
      $ref: '../common/securitySchemes.yml#/appId'
    apiKey:
      $ref: '../common/securitySchemes.yml#/apiKey'
servers:
  - url: https://data.{region}.algolia.com
    variables:
      region:
        enum:
          - us
        default: us
security:
  - appId: []
    apiKey: []
tags:
  - name: authentications
    x-displayName: Authentications
    description: An authentication describe the way we connect to Algolia, or any supported connector.
  - name: destinations
    x-displayName: Destinations
    description: A destination refers to an Algolia product (Search, Insight, Recommend, ...).
  - name: observability
    x-displayName: Observability
    description: The observability API associates a run to a task execution.
  - name: sources
    x-displayName: Sources
    description: A source describe the platform informations.
  - name: tasks
    x-displayName: Tasks
    description: A Task describe how we fetch the data (reindex, on-demand, subscription) from a source and how we index it on the Algolia side.
paths:
  # authentications API.
  /1/authentications:
    $ref: 'paths/authentications/authentications.yml'
  /1/authentications/search:
    $ref: 'paths/authentications/searchAuthentications.yml'
  /1/authentications/{authenticationID}:
    $ref: 'paths/authentications/authenticationID.yml'

  # destinations API.
  /1/destinations:
    $ref: 'paths/destinations/destinations.yml'
  /1/destinations/search:
    $ref: 'paths/destinations/searchDestinations.yml'
  /1/destinations/{destinationID}:
    $ref: 'paths/destinations/destinationID.yml'

  # sources API.
  /1/sources:
    $ref: 'paths/sources/sources.yml'
  /1/sources/search:
    $ref: 'paths/sources/searchSources.yml'
  /1/sources/{sourceID}:
    $ref: 'paths/sources/sourceID.yml'

  # tasks API.
  /1/tasks:
    $ref: 'paths/tasks/tasks.yml'
  /1/tasks/search:
    $ref: 'paths/tasks/searchTasks.yml'
  /1/tasks/{taskID}:
    $ref: 'paths/tasks/taskID.yml'
  /1/tasks/{taskID}/run:
    $ref: 'paths/tasks/runTask.yml'
  /1/tasks/{taskID}/enable:
    $ref: 'paths/tasks/enableTask.yml'
  /1/tasks/{taskID}/disable:
    $ref: 'paths/tasks/disableTask.yml'

  # observability API.
  /1/runs:
    $ref: 'paths/runs/runs.yml'
  /1/runs/{runID}:
    $ref: 'paths/runs/runID.yml'
  /1/runs/{runID}/events:
    $ref: 'paths/runs/events/events.yml'
  /1/runs/{runID}/events/{eventID}:
    $ref: 'paths/runs/events/eventID.yml'
